<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Flowboard.Application\Flowboard.Application.csproj" />
		<ProjectReference Include="..\Flowboard.Domain\Flowboard.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
		<Content Include="Prompts\cv-extract.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Intalio.Case.Core">
			<HintPath>..\libs\Intalio.Case.Core.dll</HintPath>
		</Reference>

		<Reference Include="Intalio.Core">
			<HintPath>..\libs\Intalio.Core.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>