name: Backend CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore backend/Flowboard.sln

    - name: Build Solution
      run: dotnet build backend/Flowboard.sln --configuration Release --no-restore